#version: '2.29.2'
networks:
  my-network:
    driver: bridge

services:
  backend:
    # image: thomas-oliver/nestjs-dockerized
    networks:
      - my-network
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
    command: >
      sh -c "
      npm start dev"
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
      NODE_ENV: development
      #PORT: 3000
    ports:
      - "5555:5555"
      - "3000:3000"

      #      && npx prisma studio --port 5555
      #npx prisma migrate dev --name init &&
  frontend:
    networks:
      - my-network
    build:
      context: ./frontend
      dockerfile: Dockerfile.next
    depends_on:
      - postgres
      - backend
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
      NODE_ENV: development
      PORT: 3001
      #Backend_BASE_URL: http://backend:3000
    ports:
      - "3001:3001"
      - "5500:5500"
    volumes:
      - .:/app
    command: >
      sh -c "npm install && npm run dev"

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "35000:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    networks:
      - my-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backup:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
